# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_FSL_IMX8MM)  += icore-imx8mm-ctouch2-amp10.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += smarcore-imx8xq.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
